/*
 * BrokerBackend.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AddHardwareConfigErrorCodes {
    #[serde(rename = "HardwareConfigSlugAlreadyExists")]
    HardwareConfigSlugAlreadyExists,
    #[serde(rename = "RunnerNotFound")]
    RunnerNotFound,

}

impl std::fmt::Display for AddHardwareConfigErrorCodes {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::HardwareConfigSlugAlreadyExists => write!(f, "HardwareConfigSlugAlreadyExists"),
            Self::RunnerNotFound => write!(f, "RunnerNotFound"),
        }
    }
}

impl Default for AddHardwareConfigErrorCodes {
    fn default() -> AddHardwareConfigErrorCodes {
        Self::HardwareConfigSlugAlreadyExists
    }
}

