/*
 * BrokerBackend.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AddRunnerErrorCodes {
    #[serde(rename = "RunnerSlugAlreadyExists")]
    RunnerSlugAlreadyExists,
    #[serde(rename = "OwnerNotFound")]
    OwnerNotFound,

}

impl std::fmt::Display for AddRunnerErrorCodes {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::RunnerSlugAlreadyExists => write!(f, "RunnerSlugAlreadyExists"),
            Self::OwnerNotFound => write!(f, "OwnerNotFound"),
        }
    }
}

impl Default for AddRunnerErrorCodes {
    fn default() -> AddRunnerErrorCodes {
        Self::RunnerSlugAlreadyExists
    }
}

