/*
 * BrokerBackend.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ArtifactGetResponse {
    #[serde(rename = "artifactId")]
    pub artifact_id: uuid::Uuid,
    #[serde(rename = "createdByJobId")]
    pub created_by_job_id: uuid::Uuid,
    #[serde(rename = "jobRequestedById")]
    pub job_requested_by_id: uuid::Uuid,
    #[serde(rename = "jobForRunnerId")]
    pub job_for_runner_id: uuid::Uuid,
    #[serde(rename = "displayIdentifier", deserialize_with = "Option::deserialize")]
    pub display_identifier: Option<String>,
    #[serde(rename = "createdAt")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
}

impl ArtifactGetResponse {
    pub fn new(artifact_id: uuid::Uuid, created_by_job_id: uuid::Uuid, job_requested_by_id: uuid::Uuid, job_for_runner_id: uuid::Uuid, display_identifier: Option<String>, created_at: chrono::DateTime<chrono::FixedOffset>) -> ArtifactGetResponse {
        ArtifactGetResponse {
            artifact_id,
            created_by_job_id,
            job_requested_by_id,
            job_for_runner_id,
            display_identifier,
            created_at,
        }
    }
}

