/*
 * BrokerBackend.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ArtifactAddError {
    #[serde(rename = "errorCode")]
    pub error_code: models::ArtifactAddErrorCodes,
    #[serde(rename = "errorMessage", deserialize_with = "Option::deserialize")]
    pub error_message: Option<String>,
}

impl ArtifactAddError {
    pub fn new(error_code: models::ArtifactAddErrorCodes, error_message: Option<String>) -> ArtifactAddError {
        ArtifactAddError {
            error_code,
            error_message,
        }
    }
}

