/*
 * BrokerBackend.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ArtifactGetErrorCodes {
    #[serde(rename = "ArtifactNotFound")]
    ArtifactNotFound,

}

impl std::fmt::Display for ArtifactGetErrorCodes {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::ArtifactNotFound => write!(f, "ArtifactNotFound"),
        }
    }
}

impl Default for ArtifactGetErrorCodes {
    fn default() -> ArtifactGetErrorCodes {
        Self::ArtifactNotFound
    }
}

