/*
 * BrokerBackend.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ArtifactSummary {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "displayIdentifier", deserialize_with = "Option::deserialize")]
    pub display_identifier: Option<String>,
}

impl ArtifactSummary {
    pub fn new(id: uuid::Uuid, display_identifier: Option<String>) -> ArtifactSummary {
        ArtifactSummary {
            id,
            display_identifier,
        }
    }
}

