/*
 * BrokerBackend.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ArtifactAddErrorCodes {
    #[serde(rename = "JobNotFound")]
    JobNotFound,
    #[serde(rename = "RunnerNotAssignedToJob")]
    RunnerNotAssignedToJob,
    #[serde(rename = "FileError")]
    FileError,

}

impl std::fmt::Display for ArtifactAddErrorCodes {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::JobNotFound => write!(f, "JobNotFound"),
            Self::RunnerNotAssignedToJob => write!(f, "RunnerNotAssignedToJob"),
            Self::FileError => write!(f, "FileError"),
        }
    }
}

impl Default for ArtifactAddErrorCodes {
    fn default() -> ArtifactAddErrorCodes {
        Self::JobNotFound
    }
}

