/*
 * BrokerBackend.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ChangeUserInfoErrorCode {
    #[serde(rename = "UnauthorizedEdit")]
    UnauthorizedEdit,
    #[serde(rename = "EmailAlreadyUsed")]
    EmailAlreadyUsed,
    #[serde(rename = "TargetNotFound")]
    TargetNotFound,

}

impl std::fmt::Display for ChangeUserInfoErrorCode {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::UnauthorizedEdit => write!(f, "UnauthorizedEdit"),
            Self::EmailAlreadyUsed => write!(f, "EmailAlreadyUsed"),
            Self::TargetNotFound => write!(f, "TargetNotFound"),
        }
    }
}

impl Default for ChangeUserInfoErrorCode {
    fn default() -> ChangeUserInfoErrorCode {
        Self::UnauthorizedEdit
    }
}

