/*
 * BrokerBackend.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateClientKeyRequest {
    #[serde(rename = "displayName", deserialize_with = "Option::deserialize")]
    pub display_name: Option<String>,
    #[serde(rename = "expiryInDays")]
    pub expiry_in_days: i32,
}

impl CreateClientKeyRequest {
    pub fn new(display_name: Option<String>, expiry_in_days: i32) -> CreateClientKeyRequest {
        CreateClientKeyRequest {
            display_name,
            expiry_in_days,
        }
    }
}

