/*
 * BrokerBackend.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateClientKeyResponse {
    #[serde(rename = "apiKey", deserialize_with = "Option::deserialize")]
    pub api_key: Option<String>,
}

impl CreateClientKeyResponse {
    pub fn new(api_key: Option<String>) -> CreateClientKeyResponse {
        CreateClientKeyResponse {
            api_key,
        }
    }
}

