/*
 * BrokerBackend.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DeleteRunnerUserErrorCodes {
    #[serde(rename = "RunnerNotFound")]
    RunnerNotFound,
    #[serde(rename = "UserNotFound")]
    UserNotFound,
    #[serde(rename = "UserNotAdded")]
    UserNotAdded,

}

impl std::fmt::Display for DeleteRunnerUserErrorCodes {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::RunnerNotFound => write!(f, "RunnerNotFound"),
            Self::UserNotFound => write!(f, "UserNotFound"),
            Self::UserNotAdded => write!(f, "UserNotAdded"),
        }
    }
}

impl Default for DeleteRunnerUserErrorCodes {
    fn default() -> DeleteRunnerUserErrorCodes {
        Self::RunnerNotFound
    }
}

