/*
 * BrokerBackend.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FeedbackSubmitRequest {
    #[serde(rename = "content", deserialize_with = "Option::deserialize")]
    pub content: Option<String>,
    #[serde(rename = "satisfactionLevel")]
    pub satisfaction_level: models::SatisfactionLevelEnum,
}

impl FeedbackSubmitRequest {
    pub fn new(content: Option<String>, satisfaction_level: models::SatisfactionLevelEnum) -> FeedbackSubmitRequest {
        FeedbackSubmitRequest {
            content,
            satisfaction_level,
        }
    }
}

