/*
 * BrokerBackend.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FeedbackGetRequest {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "content", deserialize_with = "Option::deserialize")]
    pub content: Option<String>,
    #[serde(rename = "satisfactionLevel")]
    pub satisfaction_level: models::SatisfactionLevelEnum,
    #[serde(rename = "createdAt")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
}

impl FeedbackGetRequest {
    pub fn new(id: uuid::Uuid, content: Option<String>, satisfaction_level: models::SatisfactionLevelEnum, created_at: chrono::DateTime<chrono::FixedOffset>) -> FeedbackGetRequest {
        FeedbackGetRequest {
            id,
            content,
            satisfaction_level,
            created_at,
        }
    }
}

