/*
 * BrokerBackend.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FileRepoErrorCode {
    #[serde(rename = "FileNotFound")]
    FileNotFound,
    #[serde(rename = "IOError")]
    IoError,

}

impl std::fmt::Display for FileRepoErrorCode {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::FileNotFound => write!(f, "FileNotFound"),
            Self::IoError => write!(f, "IOError"),
        }
    }
}

impl Default for FileRepoErrorCode {
    fn default() -> FileRepoErrorCode {
        Self::FileNotFound
    }
}

