/*
 * BrokerBackend.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum GenericAuthErrorCodes {
    #[serde(rename = "NotLoggedIn")]
    NotLoggedIn,
    #[serde(rename = "InvalidId")]
    InvalidId,
    #[serde(rename = "NoJwtType")]
    NoJwtType,
    #[serde(rename = "IncorrectJwtType")]
    IncorrectJwtType,
    #[serde(rename = "NotOwnerOfResource")]
    NotOwnerOfResource,

}

impl std::fmt::Display for GenericAuthErrorCodes {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::NotLoggedIn => write!(f, "NotLoggedIn"),
            Self::InvalidId => write!(f, "InvalidId"),
            Self::NoJwtType => write!(f, "NoJwtType"),
            Self::IncorrectJwtType => write!(f, "IncorrectJwtType"),
            Self::NotOwnerOfResource => write!(f, "NotOwnerOfResource"),
        }
    }
}

impl Default for GenericAuthErrorCodes {
    fn default() -> GenericAuthErrorCodes {
        Self::NotLoggedIn
    }
}

