/*
 * BrokerBackend.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetClientKeyResponse {
    #[serde(rename = "keyId")]
    pub key_id: uuid::Uuid,
    #[serde(rename = "keyDisplayName", deserialize_with = "Option::deserialize")]
    pub key_display_name: Option<String>,
    #[serde(rename = "expiryDate")]
    pub expiry_date: chrono::DateTime<chrono::FixedOffset>,
}

impl GetClientKeyResponse {
    pub fn new(key_id: uuid::Uuid, key_display_name: Option<String>, expiry_date: chrono::DateTime<chrono::FixedOffset>) -> GetClientKeyResponse {
        GetClientKeyResponse {
            key_id,
            key_display_name,
            expiry_date,
        }
    }
}

