/*
 * BrokerBackend.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum GetRunnerErrorCodes {
    #[serde(rename = "RunnerNotFound")]
    RunnerNotFound,

}

impl std::fmt::Display for GetRunnerErrorCodes {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::RunnerNotFound => write!(f, "RunnerNotFound"),
        }
    }
}

impl Default for GetRunnerErrorCodes {
    fn default() -> GetRunnerErrorCodes {
        Self::RunnerNotFound
    }
}

