/*
 * BrokerBackend.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum GetSourceErrorCodes {
    #[serde(rename = "SourceNotFound")]
    SourceNotFound,

}

impl std::fmt::Display for GetSourceErrorCodes {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::SourceNotFound => write!(f, "SourceNotFound"),
        }
    }
}

impl Default for GetSourceErrorCodes {
    fn default() -> GetSourceErrorCodes {
        Self::SourceNotFound
    }
}

