/*
 * BrokerBackend.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum GetUserErrorCodes {
    #[serde(rename = "UserNotFound")]
    UserNotFound,

}

impl std::fmt::Display for GetUserErrorCodes {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::UserNotFound => write!(f, "UserNotFound"),
        }
    }
}

impl Default for GetUserErrorCodes {
    fn default() -> GetUserErrorCodes {
        Self::UserNotFound
    }
}

