/*
 * BrokerBackend.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HardwareConfigGetResponse {
    #[serde(rename = "hardwareConfigId")]
    pub hardware_config_id: uuid::Uuid,
    #[serde(rename = "hardwareConfigName", deserialize_with = "Option::deserialize")]
    pub hardware_config_name: Option<String>,
    #[serde(rename = "hardwareConfigDescription", deserialize_with = "Option::deserialize")]
    pub hardware_config_description: Option<String>,
    #[serde(rename = "hardwareConfigSlug", deserialize_with = "Option::deserialize")]
    pub hardware_config_slug: Option<String>,
}

impl HardwareConfigGetResponse {
    pub fn new(hardware_config_id: uuid::Uuid, hardware_config_name: Option<String>, hardware_config_description: Option<String>, hardware_config_slug: Option<String>) -> HardwareConfigGetResponse {
        HardwareConfigGetResponse {
            hardware_config_id,
            hardware_config_name,
            hardware_config_description,
            hardware_config_slug,
        }
    }
}

