/*
 * BrokerBackend.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HardwareConfigUpdateRequest {
    #[serde(rename = "hardwareConfigName", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub hardware_config_name: Option<Option<String>>,
    #[serde(rename = "hardwareConfigDescription", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub hardware_config_description: Option<Option<String>>,
}

impl HardwareConfigUpdateRequest {
    pub fn new() -> HardwareConfigUpdateRequest {
        HardwareConfigUpdateRequest {
            hardware_config_name: None,
            hardware_config_description: None,
        }
    }
}

