/*
 * BrokerBackend.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JobGetResponse {
    #[serde(rename = "jobId")]
    pub job_id: uuid::Uuid,
    #[serde(rename = "requestedById")]
    pub requested_by_id: uuid::Uuid,
    #[serde(rename = "forRunnerId")]
    pub for_runner_id: uuid::Uuid,
    #[serde(rename = "codeSourceId")]
    pub code_source_id: uuid::Uuid,
    #[serde(rename = "usingHardwareSlug", deserialize_with = "Option::deserialize")]
    pub using_hardware_slug: Option<String>,
    #[serde(rename = "usingImageSlug", deserialize_with = "Option::deserialize")]
    pub using_image_slug: Option<String>,
    #[serde(rename = "status")]
    pub status: models::JobStatusEnum,
    #[serde(rename = "statusMessage", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub status_message: Option<Option<String>>,
    #[serde(rename = "createdAt")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "updatedAt")]
    pub updated_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "artifacts", deserialize_with = "Option::deserialize")]
    pub artifacts: Option<Vec<models::ArtifactSummary>>,
}

impl JobGetResponse {
    pub fn new(job_id: uuid::Uuid, requested_by_id: uuid::Uuid, for_runner_id: uuid::Uuid, code_source_id: uuid::Uuid, using_hardware_slug: Option<String>, using_image_slug: Option<String>, status: models::JobStatusEnum, created_at: chrono::DateTime<chrono::FixedOffset>, updated_at: chrono::DateTime<chrono::FixedOffset>, artifacts: Option<Vec<models::ArtifactSummary>>) -> JobGetResponse {
        JobGetResponse {
            job_id,
            requested_by_id,
            for_runner_id,
            code_source_id,
            using_hardware_slug,
            using_image_slug,
            status,
            status_message: None,
            created_at,
            updated_at,
            artifacts,
        }
    }
}

