/*
 * BrokerBackend.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum JobGetErrorCodes {
    #[serde(rename = "JobNotFound")]
    JobNotFound,

}

impl std::fmt::Display for JobGetErrorCodes {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::JobNotFound => write!(f, "JobNotFound"),
        }
    }
}

impl Default for JobGetErrorCodes {
    fn default() -> JobGetErrorCodes {
        Self::JobNotFound
    }
}

