/*
 * BrokerBackend.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum LoginErrorCodes {
    #[serde(rename = "InvalidCredentials")]
    InvalidCredentials,

}

impl std::fmt::Display for LoginErrorCodes {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::InvalidCredentials => write!(f, "InvalidCredentials"),
        }
    }
}

impl Default for LoginErrorCodes {
    fn default() -> LoginErrorCodes {
        Self::InvalidCredentials
    }
}

