/*
 * BrokerBackend.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LoginRequest {
    #[serde(rename = "email", deserialize_with = "Option::deserialize")]
    pub email: Option<String>,
    #[serde(rename = "password", deserialize_with = "Option::deserialize")]
    pub password: Option<String>,
}

impl LoginRequest {
    pub fn new(email: Option<String>, password: Option<String>) -> LoginRequest {
        LoginRequest {
            email,
            password,
        }
    }
}

