/*
 * BrokerBackend.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LoginError {
    #[serde(rename = "errorCode")]
    pub error_code: models::LoginErrorCodes,
    #[serde(rename = "errorMessage", deserialize_with = "Option::deserialize")]
    pub error_message: Option<String>,
}

impl LoginError {
    pub fn new(error_code: models::LoginErrorCodes, error_message: Option<String>) -> LoginError {
        LoginError {
            error_code,
            error_message,
        }
    }
}

