/*
 * BrokerBackend.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RegisterErrorCodes {
    #[serde(rename = "UserAlreadyExists")]
    UserAlreadyExists,

}

impl std::fmt::Display for RegisterErrorCodes {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::UserAlreadyExists => write!(f, "UserAlreadyExists"),
        }
    }
}

impl Default for RegisterErrorCodes {
    fn default() -> RegisterErrorCodes {
        Self::UserAlreadyExists
    }
}

