/*
 * BrokerBackend.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RunnerSessionRequest {
    #[serde(rename = "runnerSlug", deserialize_with = "Option::deserialize")]
    pub runner_slug: Option<String>,
    #[serde(rename = "runnerApiKey", deserialize_with = "Option::deserialize")]
    pub runner_api_key: Option<String>,
}

impl RunnerSessionRequest {
    pub fn new(runner_slug: Option<String>, runner_api_key: Option<String>) -> RunnerSessionRequest {
        RunnerSessionRequest {
            runner_slug,
            runner_api_key,
        }
    }
}

