/*
 * BrokerBackend.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SatisfactionLevelEnum {
    #[serde(rename = "VeryDissatisfied")]
    VeryDissatisfied,
    #[serde(rename = "Dissatisfied")]
    Dissatisfied,
    #[serde(rename = "Neutral")]
    Neutral,
    #[serde(rename = "Satisfied")]
    Satisfied,
    #[serde(rename = "VerySatisfied")]
    VerySatisfied,

}

impl std::fmt::Display for SatisfactionLevelEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::VeryDissatisfied => write!(f, "VeryDissatisfied"),
            Self::Dissatisfied => write!(f, "Dissatisfied"),
            Self::Neutral => write!(f, "Neutral"),
            Self::Satisfied => write!(f, "Satisfied"),
            Self::VerySatisfied => write!(f, "VerySatisfied"),
        }
    }
}

impl Default for SatisfactionLevelEnum {
    fn default() -> SatisfactionLevelEnum {
        Self::VeryDissatisfied
    }
}

