/*
 * BrokerBackend.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SimpleRunnerGetResponse {
    #[serde(rename = "runnerId")]
    pub runner_id: uuid::Uuid,
    #[serde(rename = "runnerName", deserialize_with = "Option::deserialize")]
    pub runner_name: Option<String>,
    #[serde(rename = "runnerDescription", deserialize_with = "Option::deserialize")]
    pub runner_description: Option<String>,
    #[serde(rename = "runnerSlug", deserialize_with = "Option::deserialize")]
    pub runner_slug: Option<String>,
}

impl SimpleRunnerGetResponse {
    pub fn new(runner_id: uuid::Uuid, runner_name: Option<String>, runner_description: Option<String>, runner_slug: Option<String>) -> SimpleRunnerGetResponse {
        SimpleRunnerGetResponse {
            runner_id,
            runner_name,
            runner_description,
            runner_slug,
        }
    }
}

