/*
 * BrokerBackend.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SourceGetResponse {
    #[serde(rename = "sourceId")]
    pub source_id: uuid::Uuid,
    #[serde(rename = "uploadedById")]
    pub uploaded_by_id: uuid::Uuid,
    #[serde(rename = "forRunnerSlug", deserialize_with = "Option::deserialize")]
    pub for_runner_slug: Option<String>,
    #[serde(rename = "createdAt")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
}

impl SourceGetResponse {
    pub fn new(source_id: uuid::Uuid, uploaded_by_id: uuid::Uuid, for_runner_slug: Option<String>, created_at: chrono::DateTime<chrono::FixedOffset>) -> SourceGetResponse {
        SourceGetResponse {
            source_id,
            uploaded_by_id,
            for_runner_slug,
            created_at,
        }
    }
}

