/*
 * BrokerBackend.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum UpdateHardwareConfigErrorCodes {
    #[serde(rename = "HardwareConfigNotFound")]
    HardwareConfigNotFound,

}

impl std::fmt::Display for UpdateHardwareConfigErrorCodes {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::HardwareConfigNotFound => write!(f, "HardwareConfigNotFound"),
        }
    }
}

impl Default for UpdateHardwareConfigErrorCodes {
    fn default() -> UpdateHardwareConfigErrorCodes {
        Self::HardwareConfigNotFound
    }
}

