/*
 * BrokerBackend.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum UserRoleEnum {
    #[serde(rename = "Admin")]
    Admin,
    #[serde(rename = "Regular")]
    Regular,

}

impl std::fmt::Display for UserRoleEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Admin => write!(f, "Admin"),
            Self::Regular => write!(f, "Regular"),
        }
    }
}

impl Default for UserRoleEnum {
    fn default() -> UserRoleEnum {
        Self::Admin
    }
}

