/*
 * BrokerBackend.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserSessionResponse {
    #[serde(rename = "token", deserialize_with = "Option::deserialize")]
    pub token: Option<String>,
}

impl UserSessionResponse {
    pub fn new(token: Option<String>) -> UserSessionResponse {
        UserSessionResponse {
            token,
        }
    }
}

