/*
 * BrokerBackend.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserSessionRequest {
    #[serde(rename = "userEmail", deserialize_with = "Option::deserialize")]
    pub user_email: Option<String>,
    #[serde(rename = "clientApiKey", deserialize_with = "Option::deserialize")]
    pub client_api_key: Option<String>,
}

impl UserSessionRequest {
    pub fn new(user_email: Option<String>, client_api_key: Option<String>) -> UserSessionRequest {
        UserSessionRequest {
            user_email,
            client_api_key,
        }
    }
}

