/*
 * BrokerBackend.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserAddRequest {
    #[serde(rename = "name", deserialize_with = "Option::deserialize")]
    pub name: Option<String>,
    #[serde(rename = "email", deserialize_with = "Option::deserialize")]
    pub email: Option<String>,
    #[serde(rename = "password", deserialize_with = "Option::deserialize")]
    pub password: Option<String>,
    #[serde(rename = "role", skip_serializing_if = "Option::is_none")]
    pub role: Option<models::UserRoleEnum>,
}

impl UserAddRequest {
    pub fn new(name: Option<String>, email: Option<String>, password: Option<String>) -> UserAddRequest {
        UserAddRequest {
            name,
            email,
            password,
            role: None,
        }
    }
}

