/*
 * BrokerBackend.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};
use tokio::fs::File as TokioFile;
use tokio_util::codec::{BytesCodec, FramedRead};


/// struct for typed errors of method [`runner_api_artifact_job_job_id_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RunnerApiArtifactJobJobIdPostError {
    Status400(models::ArtifactAddError),
    Status401(models::ProblemDetails),
    Status403(models::GenericAuthError),
    UnknownValue(serde_json::Value),
}


pub async fn runner_api_artifact_job_job_id_post(configuration: &configuration::Configuration, job_id: &str, display_identifier: &str, file_name: &str, artifact_file: impl Into<reqwest::Body>) -> Result<models::ArtifactGetResponse, Error<RunnerApiArtifactJobJobIdPostError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_job_id = job_id;
    let p_query_display_identifier = display_identifier;

    let uri_str = format!("{}/runner_api/artifact/job/{jobId}", configuration.base_path, jobId=crate::apis::urlencode(p_path_job_id));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    req_builder = req_builder.query(&[("DisplayIdentifier", &p_query_display_identifier.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    let mut multipart_form = reqwest::multipart::Form::new();
    
    let file_part = reqwest::multipart::Part::stream(artifact_file.into()).file_name(file_name.to_string());
    multipart_form = multipart_form.part("artifactFile", file_part);
    
    req_builder = req_builder.multipart(multipart_form);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ArtifactGetResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ArtifactGetResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<RunnerApiArtifactJobJobIdPostError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

